# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Download Nextflow
    init: curl -s https://get.nextflow.io | bash
    command: |
      chmod +x nextflow
      sudo mv nextflow /usr/local/bin/
      nextflow info
